OSPFv2: fix DbDesc LSAheader parse
gopacket/gopacket pull request #56
Opened 2024-04-11 02:40 UTC by povsister

This is a bugfix.
Since the origin upstream maintained by google is stall for a long time, I just submit the fix here.
There might be more contributes to OSPFv2 because I am currently working on it.

According to [RFC 2328 A.4.1](https://datatracker.ietf.org/doc/html/rfc2328#autoid-28)
The `LSType` field should be located at 4th byte of LSAheader.
and the missing LSOptions field should be at 3th.

2024-04-11 03:16 UTC, mosajjal commented
Hi. thanks for this. please add a test packet that'll fail with `master` and will pass with your commit as well.

2024-04-11 04:06 UTC, povsister commented
> Hi. thanks for this. please add a test packet that'll fail with `master` and will pass with your commit as well.

Added. PTAL

2024-05-24 23:25 UTC, mosajjal requested changes
[RFC 5340's LSA header](https://www.rfc-editor.org/rfc/rfc5340.html#appendix-A.4.2)  differs from [RFC 2328's LSA header](https://www.rfc-editor.org/rfc/rfc2328.html#appendix-A.4.1). One has the Options byte, one doesn't. We need a few tests specifically for IPv6 and OSPFv2 if it doesn't exist already.

2024-05-28 03:23 UTC, povsister commented
> One has the Options byte, one doesn't.
Yes, it is. However, OSPFv2 and v3 are not compatible within a network configuration, in other words, they do not directly communicate with each other: v2 instances can only communicate with v2, and v3 can only communicate with v3.

> We need a few tests specifically for IPv6 and OSPFv2 if it doesn't exist already.
Please refer to my explanation above. OSPFv2 with IPv6 are not impossible in a real OSPF configuration. So I don't think there is any necessary to add such test cases.

2024-11-09 21:40 UTC, mosajjal approved these changes

2024-11-09 21:40 UTC, merged