Add RRSIG and DNSKEY record types to DNS layer
gopacket/gopacket pull request #92
Opened 2024-10-17 03:37 UTC by TochusC

This pull request introduces support for RRSIG and DNSKEY record types in the DNS layer. The changes include the addition of these record types to the DNSType enumeration, as well as the implementation of their respective structures, encoding methods, and size calculations. This enhancement allows for better handling of DNSSEC-related records, improving the overall functionality of the DNS module.

2024-10-17 13:06 UTC, TochusC commented
I have tested it in my environment, and it appears to work fine.
![db2c8181-c868-4ccb-8300-80ced266fb7b](https://github.com/user-attachments/assets/e8ecda64-da5b-4676-bcec-0aede338f649)

2024-10-17 13:20 UTC, TochusC commented
Issue can be found here: #91

2024-10-19 22:23 UTC, mosajjal requested changes
looks good. can you please added a few packets with and without DNSSEC to the test files as well.

2024-10-21 11:25 UTC, TochusC commented
OK, I will finish it asap.

2024-10-24 07:35 UTC, TochusC commented
Done.
I am working to add more DNSSEC types like DS, NSEC, NSEC3.

2024-10-25 07:09 UTC, mosajjal approved these changes

2024-10-25 07:11 UTC, merged